// BTP · api/_activos.js — listas seleccionadas del Buscador para ETF, índices y cripto (02/10/2026).
// Seleccionadas por Belar y ampliables a mano: una entrada por línea. Validadas contra Yahoo el 02/10/2026.
// ETF: [símbolo, categoría, UCITS (1/0), acumulación (1/0), qué replica]. Los no UCITS (EE. UU.) van como referencia:
// un minorista europeo no puede comprarlos (PRIIPs/KID), salvo como CFD.
export const ETF = [
  ["CSPX.L", "Índice amplio", 1, 1, "S&P 500"],
  ["VUAA.L", "Índice amplio", 1, 1, "S&P 500"],
  ["SXR8.DE", "Índice amplio", 1, 1, "S&P 500"],
  ["CNDX.L", "Índice amplio", 1, 1, "Nasdaq 100"],
  ["SXRV.DE", "Índice amplio", 1, 1, "Nasdaq 100"],
  ["EQQQ.L", "Índice amplio", 1, 0, "Nasdaq 100"],
  ["IWDA.L", "Índice amplio", 1, 1, "MSCI World"],
  ["EUNL.DE", "Índice amplio", 1, 1, "MSCI World"],
  ["SWRD.L", "Índice amplio", 1, 1, "MSCI World"],
  ["VWRA.L", "Índice amplio", 1, 1, "FTSE All-World"],
  ["VWCE.DE", "Índice amplio", 1, 1, "FTSE All-World"],
  ["SSAC.L", "Índice amplio", 1, 1, "MSCI ACWI"],
  ["EIMI.L", "Índice amplio", 1, 1, "MSCI EM IMI"],
  ["IS3N.DE", "Índice amplio", 1, 1, "MSCI EM IMI"],
  ["IUSN.DE", "Índice amplio", 1, 1, "MSCI World Small Cap"],
  ["ZPRV.DE", "Índice amplio", 1, 1, "USA Small Cap Value"],
  ["R2US.L", "Índice amplio", 1, 1, "Russell 2000"],
  ["MEUD.PA", "Índice amplio", 1, 1, "Stoxx Europe 600"],
  ["EXSA.DE", "Índice amplio", 1, 0, "Stoxx Europe 600"],
  ["CSX5.L", "Índice amplio", 1, 1, "Euro Stoxx 50"],
  ["SXRT.DE", "Índice amplio", 1, 1, "Euro Stoxx 50"],
  ["XDEW.DE", "Índice amplio", 1, 1, "S&P 500 Equal Weight"],
  ["IUQA.L", "Factor", 1, 1, "MSCI USA Quality"],
  ["IWMO.L", "Factor", 1, 1, "MSCI World Momentum"],
  ["IWVL.L", "Factor", 1, 1, "MSCI World Value"],
  ["CSKR.L", "País/Región", 1, 1, "MSCI Korea"],
  ["SJPA.L", "País/Región", 1, 1, "MSCI Japan"],
  ["CNYA.L", "País/Región", 1, 1, "MSCI China A"],
  ["NDIA.L", "País/Región", 1, 1, "MSCI India"],
  ["IBZL.L", "País/Región", 1, 0, "MSCI Brazil"],
  ["LTAM.L", "País/Región", 1, 0, "MSCI EM Latin America"],
  ["LYXIB.MC", "País/Región", 1, 0, "IBEX 35"],
  ["EXS1.DE", "País/Región", 1, 1, "DAX"],
  ["ISF.L", "País/Región", 1, 0, "FTSE 100"],
  ["CPJ1.L", "País/Región", 1, 1, "MSCI Pacific ex-Japan"],
  ["IUIT.L", "Sector", 1, 1, "S&P 500 Tecnología"],
  ["IUHC.L", "Sector", 1, 1, "S&P 500 Salud"],
  ["IUFS.L", "Sector", 1, 1, "S&P 500 Financiero"],
  ["IUES.L", "Sector", 1, 1, "S&P 500 Energía"],
  ["IUCD.L", "Sector", 1, 1, "S&P 500 Consumo discrecional"],
  ["IUCS.L", "Sector", 1, 1, "S&P 500 Consumo básico"],
  ["IUIS.L", "Sector", 1, 1, "S&P 500 Industria"],
  ["IUMS.L", "Sector", 1, 1, "S&P 500 Materiales"],
  ["IUUS.L", "Sector", 1, 1, "S&P 500 Utilities"],
  ["IUCM.L", "Sector", 1, 1, "S&P 500 Comunicación"],
  ["SMH.L", "Temático", 1, 1, "Semiconductores"],
  ["VVSM.DE", "Temático", 1, 1, "Semiconductores"],
  ["DFNS.L", "Temático", 1, 1, "Defensa"],
  ["URNU.L", "Temático", 1, 1, "Uranio"],
  ["GDX.L", "Temático", 1, 0, "Mineras de oro"],
  ["INRG.L", "Temático", 1, 0, "Energía limpia"],
  ["EXV1.DE", "Sector", 1, 0, "Bancos Europa"],
  ["RBOT.L", "Temático", 1, 1, "Robótica e IA"],
  ["IGLN.L", "Oro y materias primas", 1, 1, "Oro físico"],
  ["SGLN.L", "Oro y materias primas", 1, 1, "Oro físico"],
  ["PHAU.L", "Oro y materias primas", 1, 1, "Oro físico"],
  ["4GLD.DE", "Oro y materias primas", 1, 1, "Oro físico (Xetra-Gold)"],
  ["PHAG.L", "Oro y materias primas", 1, 1, "Plata física"],
  ["COPA.L", "Oro y materias primas", 1, 1, "Cobre"],
  ["BRNT.L", "Oro y materias primas", 1, 1, "Petróleo Brent"],
  ["CMOD.L", "Oro y materias primas", 1, 1, "Materias primas diversificadas"],
  ["IB01.L", "Bonos", 1, 1, "Letras EE. UU. 0-1 años"],
  ["IBTA.L", "Bonos", 1, 1, "Tesoro EE. UU. 1-3 años"],
  ["DTLA.L", "Bonos", 1, 1, "Tesoro EE. UU. 20+ años"],
  ["IGLT.L", "Bonos", 1, 0, "Gilts"],
  ["IEAC.L", "Bonos", 1, 0, "Corporativos euro"],
  ["SPY", "Índice amplio", 0, 0, "S&P 500 (EE. UU.)"],
  ["QQQ", "Índice amplio", 0, 0, "Nasdaq 100 (EE. UU.)"],
  ["IWM", "Índice amplio", 0, 0, "Russell 2000 (EE. UU.)"],
  ["EWY", "País/Región", 0, 0, "MSCI Korea (EE. UU.)"],
  ["EWJ", "País/Región", 0, 0, "MSCI Japan (EE. UU.)"],
  ["FXI", "País/Región", 0, 0, "China large cap (EE. UU.)"],
  ["EWZ", "País/Región", 0, 0, "MSCI Brazil (EE. UU.)"],
  ["GLD", "Oro y materias primas", 0, 0, "Oro (EE. UU.)"],
  ["XLE", "Sector", 0, 0, "Energía (EE. UU.)"],
  ["XLK", "Sector", 0, 0, "Tecnología (EE. UU.)"],
  ["IGV", "Sector", 0, 0, "Software (EE. UU.)"],
  ["URA", "Temático", 0, 0, "Uranio (EE. UU.)"],
]

// Índices: [símbolo, región, ETF UCITS con el que se replica o null]. No se operan: contexto de mercado.
export const INDICE = [
  ["^GSPC", "EE. UU.", "CSPX.L"],
  ["^NDX", "EE. UU.", "CNDX.L"],
  ["^DJI", "EE. UU.", null],
  ["^RUT", "EE. UU.", "R2US.L"],
  ["^VIX", "EE. UU.", null],
  ["^STOXX50E", "Europa", "CSX5.L"],
  ["^STOXX", "Europa", "MEUD.PA"],
  ["^GDAXI", "Europa", "EXS1.DE"],
  ["^FCHI", "Europa", null],
  ["^IBEX", "Europa", "LYXIB.MC"],
  ["^FTSE", "Europa", "ISF.L"],
  ["FTSEMIB.MI", "Europa", null],
  ["^AEX", "Europa", null],
  ["^SSMI", "Europa", null],
  ["^N225", "Asia", "SJPA.L"],
  ["^KS11", "Asia", "CSKR.L"],
  ["^HSI", "Asia", null],
  ["000001.SS", "Asia", "CNYA.L"],
  ["^TWII", "Asia", null],
  ["^BSESN", "Asia", "NDIA.L"],
  ["^AXJO", "Asia", null],
  ["^BVSP", "Latinoamérica", "IBZL.L"],
  ["^MXX", "Latinoamérica", null],
  ["^GSPTSE", "América", null],
  ["DX-Y.NYB", "Macro", null],
  ["^TNX", "Macro", "DTLA.L"],
  ["GC=F", "Macro", "IGLN.L"],
  ["SI=F", "Macro", "PHAG.L"],
  ["CL=F", "Macro", "BRNT.L"],
  ["BZ=F", "Macro", "BRNT.L"],
  ["HG=F", "Macro", "COPA.L"],
]

// Cripto: top por capitalización + el vehículo de bróker del bloque BTC (VBTC.DE).
export const CRIPTO = [
  "BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "BNB-USD", "ADA-USD", "DOGE-USD", "AVAX-USD", "LINK-USD", "DOT-USD", "LTC-USD", "TRX-USD", "TON11419-USD", "SUI20947-USD", "XLM-USD", "BCH-USD", "HBAR-USD", "NEAR-USD", "UNI7083-USD", "AAVE-USD", "VBTC.DE"
]
